export const NEW_PUBLICACION_REQUEST="NEW_PUBLICACION_REQUEST"
export const NEW_PUBLICACION_SUCCESS="NEW_PUBLICACION_SUCCESS"
export const NEW_PUBLICACION_FAIL="NEW_PUBLICACION_FAIL"

export const GET_PUBLICACIONES_REQUEST="GET_PUBLICACIONES_REQUEST"
export const GET_PUBLICACIONES_SUCCESS="GET_PUBLICACIONES_SUCCESS"
export const GET_PUBLICACIONES_FAIL="GET_PUBLICACIONES_FAIL"


export const CLEAR_ERRORS="CLEAR_ERRORS"
